packages:
  - "apps/*"
  - "packages/*"

catalog:
    lucide-react: ^0.542.0
    tailwindcss: ^4.1.12
    eslint: ^9.33.0
    typescript: ~5.8.3
    "@types/node": ^22.18.0
  
catalogs:
    react19:
       react: ^19.1.1
       react-dom: ^19.1.1
       "@types/react": ^19.1.10
       "@types/react-dom": ^19.1.7

