services:
  - type: web
    name: vibeo-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./apps/api/Dockerfile
    buildFilter:
      paths:
       - apps/api/**
       - packages/**
    envVars:
       - key: NODE_ENV
         value: production
       - key: PORT
         value: 3001
       - key: DATABASE_URL
         sync: false
       - key: JWT_SECRET
         sync: false
       - key: ALLOWED_ORIGIN
         fromService:
           name: vibeo
           type: web
           property: host

  - type: web
    name: vibeo
    runtime: docker
    dockerContext: .
    dockerfilePath: ./apps/web/Dockerfile
    buildFilter:
      paths:
        - apps/web/**
        - packages/**
    envVars:
     - key: VITE_API_URL
       fromService:
        name: vibeo-backend
        type: web
        property: host